# Generated by Django 2.0.1 on 2018-06-27 19:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('productPrice', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')])),
                ('productURL', models.URLField(max_length=2000, unique=True)),
                ('productImage', models.ImageField(max_length=1000, null=True, upload_to='assets/images/products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'fpx', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'mic', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])])),
            ],
        ),
    ]
